### ISSUE TITLE
Orion crashes when there are many GeoProperty items.

### ISSUE THREAD

**Issue by ctc-enokida** [Fiware/context.Orion-LD#922]
When creating entities for OrionLD, Orion LD will crash if the number of GeoProperty type items is greater than 100.

This happens not only in the usual case of creating an entity with more than 100 GeoProperty, but also when the total number of GeoProperty contained in multiple entities in a Batch operation exceeds 100.
The error message will be 502 Bad Gateway.

Is there a workaround?

Thank you.

**Comment by kzangeli** [comment]
Thanks for reporting!
Yeah this is an error, part of the code that isn't fully implemented.
I'm on it !

**Comment by kzangeli** [comment]
Hopefully fixed with PR https://github.com/FIWARE/context.Orion-LD/pull/923
Please try again, once the PR is merged (and docker image pushed) and let me know.

**Comment by ctc-enokida** [comment]
Thank you for your quick response.
 I'll look forward to waiting for new docker image.

 Thank you.

**Comment by kzangeli** [comment]
The fix is done, you can test it and let me know.
The tests I did was to create 50 entities with 10 geo-properties each, and that failed before the fix (SIGSEGV) and is now working.
It's not a very thorough test :)... so, I'd like to hear from you before we close the issue.

**Comment by ctc-enokida** [comment]
Thanks for the fix.
Should I test with the latest version of docker?
I'll test it and get back to you.

**Comment by ctc-enokida** [comment]
I tested it with the latest version of Docker, but it did not resolve the issue and crashed.

■My environment
・Orion
　 ：fiware/orion-ld:latest
・Mongo
　：mongo:3.6
（https://hub.docker.com/r/fiware/orion-ld）

I tested the following environment, and it seems to register without crashing.
Is there any change in the version of Mongo that should be used with OrionLd?

■Environment
・Orion
　：fiware/orion-ld:latest
・Mongo
 　：mongo:4.4

**Comment by ctc-enokida** [comment]
How is the investigation after than going?

And...
I just tried Docker's latest and some of the tags, and it seems that the feature you fixed is disabled.
Please let me know if there are any tags that have the GeoProperty bug fixed now.

If possible, I would also like to know what version of MongoDB I should combine.

**Comment by kzangeli** [comment]
ok ...
I did fix it and my functest with ~900 geo properties works just fine.
I guess you're doing something slightly different.

To fix the problem I need to be able to reproduce it, so, please post all the details on how you manage to crash the broker and I'll look into it.
I'd need access to the complete detail of all the requests that provoke the crash.
Depending on the size of all this, not sure a github issue is the best place to hold all the info ...

**Comment by kzangeli** [comment]
About the mongo version, there's no fix version. It depends on where you run the broker.
For example, I think Ubuntu 20.04 only supports mongo 4.4 and newer.
As long as you're using a version GTE 3.6 it should work.

**Comment by ctc-enokida** [comment]
Thanks for the reply and suggestions.

Hmmm.
I'm currently using a variety of tags.
I can't seem to get it to work in either mongoDB 3.6 or 4.4.
I will sort out the situation and let you know how I am implementing it.
Thanks.

**Comment by kzangeli** [comment]
What if you compare what I do in my functest (https://github.com/FIWARE/context.Orion-LD/pull/923/files#diff-85d4093e08ca1bd5c2e13a6e59f8b6a94fb2746f11afa6a57c675378dac9fbeaR1) with what you do ?

There's surely a difference and in that may lie the problem.

Start with something as close as possible to "what I do", and if that works, go little by little towards "what you do".
When it starts failing, there we have the problem.

**Comment by ctc-enokida** [comment]
Thanks for the info.

Your test went well. 
You are right, there seems to be a difference between my test and yours.

I will try different patterns and identify the conditions when it fails and get back to you.
Sorry if it takes a while to get back to you.

**Comment by kzangeli** [comment]
ok, happy to hear that.
When you find the difference that provokes the crash, you've discovered an important bug in the broker and with enough info, it's usually a quick fix :)

**Comment by ctc-enokida** [comment]
It seems that my @context file was not good.
Sorry about that.

After trying various patterns, I found that the crash only occurred for a specific TYPE defined in my @context file.
In the @context file, there was an item defined with the same name as the TYPE.
Example ) type: Book & item: book

In this case, the crash occurs when the number of items exceeds a certain level.
（If the number of items was small, it could be registered without any problem.）

I'm going to do some more research and try to identify the cause of the problem.
(Maybe next week.)
Is there anything in the logic of the process that rings a bell?


I probably changed the @context file before and after the last time I checked your bug fix, and it turned out to be a weird query. Sorry.

**Comment by kzangeli** [comment]
ok!
Different bug, still highly interesting.
The broker can never crash, whatever you throw at it, so, please let me know what you find and I will try to fix it!

Don't feel sorry for finding bugs for me :)
I am very grateful !

**Comment by ctc-enokida** [comment]
Thank you.
I'm always grateful for that, too.

I'll contact you when I know more.

**Comment by ctc-enokida** [comment]
As a result of additional checks, the following events were confirmed and will be shared.

①.
When GeoProperty is included in the items specified in @context, it crashes when there are more than 23 items.
※　This occurred regardless of whether the item name (location) was initially defined in Orionld, or whether it was a uniquely defined item (location1).
②
Crash does not occur if items not specified in @context are added to the request in ①.


I will share the command I ran.
①
・[curl-case-1.txt](https://github.com/FIWARE/context.Orion-LD/files/7334884/curl-case-1.txt)：CURL containing location (crash)
・[curl-case-2.txt](https://github.com/FIWARE/context.Orion-LD/files/7334888/curl-case-2.txt)：CURL containing a custom-defined location1 (crash)
②
・[curl-case-3.txt](https://github.com/FIWARE/context.Orion-LD/files/7334893/curl-case-3.txt)
：Add an item (testAttr) that is not defined anywhere in @context to curl-case-2 (no crash)

・[test-context-ngsi.json](https://github.com/FIWARE/context.Orion-LD/files/7334895/test-context-ngsi.txt)：@context file that is referenced in CURL

■ environment
・[docker-compose.yml](https://github.com/FIWARE/context.Orion-LD/files/7334908/docker-compose.txt)

※ The jsonld and yml files cannot be uploaded to github, so I changed the extension to txt.
I'm only masking the @context location, can you try changing it to your environment and check?

**Comment by kzangeli** [comment]
ok, great!
Now I have something to go on :)

**Comment by ctc-enokida** [comment]
Thanks for the planning.

If you have any assumptions about the timing of the confirmation, 
I would appreciate it if you could give me a rough schedule.

**Comment by kzangeli** [comment]
Yeah ... you see, I'm out on parental leave until mid November.
So, things are going a bit slower than usual.
I'll do my best to have this fixed before the end of October.

**Comment by ctc-enokida** [comment]
Oh, okay.
I'm sorry I put you through so much.

Please prioritize your parental  leave.
I'd appreciate it if you could check in with me after you get settled.
Good luck with your baby ；）

**Comment by kzangeli** [comment]
So, I'm back full-time. Finally ! :)

Had a few even more urgent issue to fix, but I'm almost done with those.
Will start with this issue tomorrow morning, if not before.

**Comment by kzangeli** [comment]
Hopefully fixed by PR #945

**Comment by ctc-enokida** [comment]
Oh, finally.
I've been waiting for you.
&Thanks for the fix.

I'll give it a try!

**Comment by ctc-enokida** [comment]
Hi.

I tested it with the latest version of docker.
I have confirmed that all the crashes I had identified have been resolved.
Thanks a lot for your support even though I am on maternity leave.

Just one more thing.
The version of MongoDB I was talking about in the beginning↑↑ wasn't dependent on this issue.
（I was wrong. Sorry.）
However, I would like to know if there is a specific MongoDB version that I should use as OrionLD.
(The versions are not available on Github or Tutorial, 
 so I would like to know which version I should use. 
The information on the version you are using for testing is also fine).
